- hosts: localhost
  vars:
    vault_user: 'cmeyers'
    job_append: "{{ lookup('env', 'BUILD_ID')|default('debug') }}"  # TODO: generate rand instead of debug
    image_tag: "{{ lookup('env', 'BAKE_BUILD_ID')|default('latest') }}"

  gather_facts: false
  tasks:
    - name: "Generate kube pod description from ansible template"
      template:
        src: "{{ playbook_dir }}/templates/unit_tests_pod.yml.j2"
        dest: "{{ playbook_dir }}/unit_tests_pod.yml"

    - name: "Instantiate kube pod"
      command: "kubectl create -f {{ playbook_dir }}/unit_tests_pod.yml"
